### ISSUE TITLE
TypeError: Promise.map is not a function after upgrade to 0.11.3

### ISSUE THREAD

**Issue by craigcartmell** [ZJONSSON/node-unzipper#305]
**Node: 18**

The error relates to `node_modules/unzipper/lib/Open/directory.js`, line 155.

```
  return Promise.map(files, function(entry) {
```

Promise.map looks like it's a feature of bluebird: http://bluebirdjs.com/docs/api/promise.map.html

I can't see that the Bluebird promise is being imported though, so it looks like it's using the native Promise, which doesn't support the .map function?

**Comment by ZJONSSON** [comment]
Thanks @craigcartmell, can you give me the specific node version and platform (linux, mac windows) and the error stack?

The line you referred to is tested on node v.10 up to v.19 https://zjonsson.github.io/node-unzipper/node-unzipper/lib/Open/directory.js.html, so it's not immediately clear to me what is going on

**Comment by ZJONSSON** [comment]
Please upgrade to 0.11.4, there was a discrepancy between published and master

**Comment by craigcartmell** [comment]
Thanks @ZJONSSON - That fixed the issue
